apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels: 
    apps: nginx
  spec:
    containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - ContainerPort: 80
      