# Correct YAML for a Pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:  # Optional: You can add labels here if needed
    app: nginx
spec: # 'spec' is a top-level field for the Pod
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80